"""glia/acl_manager.py — ACL renderer + broker reloader (spec §E.6, Task 5.5).

Renders per-region Jinja2 templates from ``bus/acl_templates/`` into a single
``bus/acl.conf`` file, then hot-reloads the mosquitto container with SIGHUP.

Template layout:
  * ``_base.j2``  — global rules; contains ``user {{ region }}`` at the top and
                    must be rendered once per region (with that region's name
                    substituted).
  * ``<region>.j2`` — per-region additional rules (no ``user`` directive).
  * ``_new_region_stub.j2`` — used by spawn_executor (task 5.7a); not
    consumed here.

Deviation from spec §E.6 pseudocode
-----------------------------------
The spec's pseudocode renders ``_base.j2`` once (no region context) and
concatenates the per-region templates afterwards.  That is inconsistent with
the actual template on disk, which contains ``{{ region }}`` and must appear
*per mosquitto-user block* (mosquitto ACLs use ``user <name>`` to scope the
rules that follow).  We therefore render ``_base.j2`` per region and prepend
each region's ``_base.j2`` output to its ``<region>.j2`` output.

Triggered by bootstrap, new-region spawn, approved code change to an ACL
template, or an operator CLI invocation.  The async supervisor wraps this
call in ``asyncio.to_thread`` where appropriate.
"""
from __future__ import annotations

import asyncio
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import docker  # type: ignore[import-untyped]
import jinja2
import structlog
from docker.errors import APIError, NotFound  # type: ignore[import-untyped]

from glia.launcher import GliaError
from glia.registry import RegionRegistry

log = structlog.get_logger(__name__)


REPO_ROOT = Path(__file__).resolve().parents[1]
BUS_DIR = REPO_ROOT / "bus"
TEMPLATE_DIR = BUS_DIR / "acl_templates"
ACL_PATH = BUS_DIR / "acl.conf"
ACL_TMP_PATH = BUS_DIR / "acl.conf.tmp"
BROKER_CONTAINER = "mosquitto"

_BASE_TEMPLATE_NAME = "_base.j2"

_HEADER = (
    "# Generated by glia acl_manager. DO NOT EDIT — will be overwritten.\n"
    "#\n"
)


@dataclass(frozen=True)
class ApplyResult:
    """Result of a render-and-apply cycle."""

    ok: bool
    path: Path | None = None
    reason: str | None = None


class AclManager:
    """Render per-region ACL templates and hot-reload mosquitto.

    Parameters
    ----------
    registry:
        Region registry instance.  ``registry.active()`` provides the default
        region list (reserved regions are always excluded).
    docker_client:
        Injected ``docker.DockerClient``-like object.  If ``None``, one is
        created lazily via ``docker.from_env()`` inside :meth:`reload_broker`.
    template_dir:
        Directory containing ``_base.j2`` and ``<region>.j2`` files.  Defaults
        to the repo's ``bus/acl_templates`` directory.
    bus_dir:
        Directory to write ``acl.conf`` (and its ``.tmp`` staging file) into.
        Defaults to the repo's ``bus/`` directory.  Tests override with
        ``tmp_path``.
    reload_sleep_s:
        Best-effort settle delay after sending SIGHUP, per spec pseudocode.
    """

    def __init__(
        self,
        registry: RegionRegistry,
        *,
        docker_client: Any | None = None,
        template_dir: Path = TEMPLATE_DIR,
        bus_dir: Path = BUS_DIR,
        reload_sleep_s: float = 0.5,
    ) -> None:
        self._registry = registry
        self._docker = docker_client
        self._template_dir = Path(template_dir)
        self._bus_dir = Path(bus_dir)
        self._reload_sleep_s = reload_sleep_s
        self._env = jinja2.Environment(
            loader=jinja2.FileSystemLoader(str(self._template_dir)),
            autoescape=False,
            undefined=jinja2.StrictUndefined,
            keep_trailing_newline=True,
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def render_all(self, regions: list[str] | None = None) -> str:
        """Render the full ``acl.conf`` body as a string.

        Does NOT write to disk.  Regions default to the active (non-reserved)
        list in registry insertion order.
        """
        if regions is None:
            regions = [e.name for e in self._registry.active()]

        per_region_blocks: list[str] = [
            self._render_region(name) for name in regions
        ]
        return _HEADER + "\n".join(per_region_blocks)

    async def render_and_apply(self) -> ApplyResult:
        """Render, consistency-check, atomic write, SIGHUP the broker."""
        regions = [e.name for e in self._registry.active()]
        per_region = [self._render_region(name) for name in regions]

        conflict = self._check_conflicts(per_region)
        if conflict is not None:
            log.warning(
                "acl_render_conflict",
                reason=conflict,
                region_count=len(regions),
            )
            return ApplyResult(ok=False, reason=f"acl conflict: {conflict}")

        body = _HEADER + "\n".join(per_region)
        self._atomic_write(body)

        await self.reload_broker()
        await asyncio.sleep(self._reload_sleep_s)

        log.info(
            "acl_applied",
            path=str(self._bus_dir / "acl.conf"),
            region_count=len(regions),
        )
        return ApplyResult(ok=True, path=self._bus_dir / "acl.conf")

    async def reload_broker(self) -> None:
        """Send SIGHUP to the mosquitto container so it re-reads acl.conf."""
        client = self._docker
        if client is None:
            try:
                client = docker.from_env()
            except Exception as exc:  # pragma: no cover - hard to simulate
                raise GliaError(
                    f"failed to initialise docker client: {exc}"
                ) from exc

        try:
            container = client.containers.get(BROKER_CONTAINER)
        except NotFound as exc:
            raise GliaError(
                f"mosquitto container {BROKER_CONTAINER!r} not found"
            ) from exc
        except APIError as exc:
            raise GliaError(
                f"docker API error while fetching {BROKER_CONTAINER!r}: {exc}"
            ) from exc

        try:
            container.kill(signal="SIGHUP")
        except APIError as exc:
            raise GliaError(
                f"docker API error while signalling {BROKER_CONTAINER!r}: {exc}"
            ) from exc

        log.info("acl_broker_reloaded", container=BROKER_CONTAINER)

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _render_region(self, region: str) -> str:
        """Render ``_base.j2`` + ``<region>.j2`` for a single region."""
        base = self._render_template(_BASE_TEMPLATE_NAME, region=region)
        extras = self._render_template(f"{region}.j2", region=region)
        # Ensure a single blank line between base rules and region-specific
        # rules so the output is readable.
        if not base.endswith("\n"):
            base += "\n"
        return base + extras

    def _render_template(self, name: str, **context: Any) -> str:
        try:
            tmpl = self._env.get_template(name)
            return tmpl.render(**context)
        except jinja2.TemplateNotFound as exc:
            raise GliaError(
                f"ACL template not found: {name!r} under {self._template_dir}"
            ) from exc
        except jinja2.UndefinedError as exc:
            raise GliaError(
                f"ACL template {name!r} references undefined variable: {exc}"
            ) from exc
        except jinja2.TemplateSyntaxError as exc:
            raise GliaError(
                f"ACL template {name!r} has syntax error: {exc}"
            ) from exc

    def _check_conflicts(self, per_region: list[str]) -> str | None:
        """Return a reason string if conflicts found, else None.

        v0 stub per spec §B.6.1.  A full implementation would parse each
        rendered block and detect duplicate topic-write claims across
        regions.  Deferred to post-v0.
        """
        log.debug(
            "acl_conflict_check_stubbed",
            block_count=len(per_region),
        )
        return None

    def _atomic_write(self, body: str) -> None:
        """Write ``body`` to ``acl.conf`` atomically via a tmp file + rename."""
        self._bus_dir.mkdir(parents=True, exist_ok=True)
        tmp = self._bus_dir / "acl.conf.tmp"
        final = self._bus_dir / "acl.conf"
        tmp.write_text(body, encoding="utf-8")
        tmp.replace(final)
