"""Unit tests for glia.acl_manager — Task 5.5.

Covers:
  * render_all produces a concatenated acl.conf with per-region sections,
    each prefixed by a `user <name>` directive from _base.j2 and followed
    by the region-specific rules.
  * Reserved regions (raphe_nuclei, locus_coeruleus, hypothalamus,
    basal_forebrain, cerebellum) are excluded.
  * Strict-undefined: a missing variable in a template surfaces as
    a GliaError.
  * Missing per-region template -> GliaError.
  * render_and_apply performs atomic write (tmp -> rename) and sends
    SIGHUP to the mosquitto container.
  * reload_broker error paths (NotFound, APIError) wrap into GliaError.
"""
from __future__ import annotations

from pathlib import Path
from unittest.mock import MagicMock

import pytest
from docker.errors import (  # type: ignore[import-untyped]
    APIError,
    NotFound,
)

from glia.acl_manager import ACL_PATH, AclManager, ApplyResult
from glia.launcher import GliaError
from glia.registry import RegionRegistry

# ---------------------------------------------------------------------------
# Shared constants
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parents[2]
REAL_TEMPLATE_DIR = REPO_ROOT / "bus" / "acl_templates"

ACTIVE_REGIONS = (
    "medial_prefrontal_cortex",
    "prefrontal_cortex",
    "anterior_cingulate",
    "hippocampus",
    "thalamus",
    "association_cortex",
    "visual_cortex",
    "auditory_cortex",
    "motor_cortex",
    "broca_area",
    "amygdala",
    "vta",
    "insula",
    "basal_ganglia",
)

RESERVED_REGIONS = (
    "raphe_nuclei",
    "locus_coeruleus",
    "hypothalamus",
    "basal_forebrain",
    "cerebellum",
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def registry() -> RegionRegistry:
    return RegionRegistry.load()


@pytest.fixture
def mock_docker_client() -> MagicMock:
    client = MagicMock(name="DockerClient")
    container = MagicMock(name="MosquittoContainer")
    client.containers.get.return_value = container
    return client


@pytest.fixture
def acl_manager(
    registry: RegionRegistry,
    mock_docker_client: MagicMock,
    tmp_path: Path,
) -> AclManager:
    return AclManager(
        registry,
        docker_client=mock_docker_client,
        template_dir=REAL_TEMPLATE_DIR,
        bus_dir=tmp_path,
        reload_sleep_s=0.0,
    )


# ---------------------------------------------------------------------------
# render_all
# ---------------------------------------------------------------------------


def test_render_all_includes_user_directives_for_each_active_region(
    acl_manager: AclManager,
) -> None:
    rendered = acl_manager.render_all()
    for name in ACTIVE_REGIONS:
        assert f"user {name}" in rendered, (
            f"missing `user {name}` directive in rendered acl.conf"
        )


def test_render_all_inlines_base_rules_per_region(
    acl_manager: AclManager,
) -> None:
    """Every region section contains the characteristic base pattern rules."""
    rendered = acl_manager.render_all()
    # pattern rules from _base.j2 are global — expect exactly one occurrence
    # in the canonical output when written literally (%c is mosquitto's
    # per-connection placeholder).
    assert rendered.count("pattern write hive/system/heartbeat/%c") == len(
        ACTIVE_REGIONS
    )
    assert rendered.count("pattern write hive/system/region_stats/%c") == len(
        ACTIVE_REGIONS
    )
    assert rendered.count("topic read hive/broadcast/#") == len(ACTIVE_REGIONS)


def test_render_all_inlines_region_specific_rules(
    acl_manager: AclManager,
) -> None:
    rendered = acl_manager.render_all()
    # amygdala's per-region rule
    assert "topic write hive/modulator/cortisol" in rendered
    # hippocampus-specific rule from hippocampus.j2 (amygdala writes this)
    assert "topic write hive/cognitive/hippocampus/encoding_hint" in rendered
    # a sampling from visual_cortex
    assert "hive/sensory/visual" in rendered


def test_render_all_generated_header_present(acl_manager: AclManager) -> None:
    rendered = acl_manager.render_all()
    assert rendered.startswith("# Generated by glia acl_manager")
    assert "DO NOT EDIT" in rendered.splitlines()[0]


def test_render_all_excludes_reserved_regions(acl_manager: AclManager) -> None:
    rendered = acl_manager.render_all()
    for reserved in RESERVED_REGIONS:
        assert f"user {reserved}" not in rendered, (
            f"reserved region {reserved} leaked into acl.conf"
        )


def test_render_all_order_stable(acl_manager: AclManager) -> None:
    """Two successive renders must produce byte-identical output."""
    a = acl_manager.render_all()
    b = acl_manager.render_all()
    assert a == b


def test_render_all_explicit_region_list(acl_manager: AclManager) -> None:
    """When passed a specific region list, only those regions appear."""
    rendered = acl_manager.render_all(regions=["amygdala", "hippocampus"])
    assert "user amygdala" in rendered
    assert "user hippocampus" in rendered
    assert "user motor_cortex" not in rendered
    assert "user prefrontal_cortex" not in rendered


# ---------------------------------------------------------------------------
# render_all error paths
# ---------------------------------------------------------------------------


def test_render_all_uses_strict_undefined_base(
    registry: RegionRegistry,
    mock_docker_client: MagicMock,
    tmp_path: Path,
) -> None:
    """Base template referencing an unknown variable must raise GliaError."""
    tmpl_dir = tmp_path / "templates"
    tmpl_dir.mkdir()
    # Base uses a variable that isn't passed (`mystery`).
    (tmpl_dir / "_base.j2").write_text(
        "user {{ region }}\n# unknown: {{ mystery }}\n"
    )
    (tmpl_dir / "amygdala.j2").write_text("topic read foo\n")

    mgr = AclManager(
        registry,
        docker_client=mock_docker_client,
        template_dir=tmpl_dir,
        bus_dir=tmp_path,
        reload_sleep_s=0.0,
    )
    with pytest.raises(GliaError):
        mgr.render_all(regions=["amygdala"])


def test_render_all_missing_region_template_raises_gliaerror(
    registry: RegionRegistry,
    mock_docker_client: MagicMock,
    tmp_path: Path,
) -> None:
    tmpl_dir = tmp_path / "templates"
    tmpl_dir.mkdir()
    (tmpl_dir / "_base.j2").write_text("user {{ region }}\n")
    # no amygdala.j2 created on purpose

    mgr = AclManager(
        registry,
        docker_client=mock_docker_client,
        template_dir=tmpl_dir,
        bus_dir=tmp_path,
        reload_sleep_s=0.0,
    )
    with pytest.raises(GliaError):
        mgr.render_all(regions=["amygdala"])


# ---------------------------------------------------------------------------
# render_and_apply
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_render_and_apply_writes_atomic(
    acl_manager: AclManager,
    mock_docker_client: MagicMock,
    tmp_path: Path,
) -> None:
    result = await acl_manager.render_and_apply()

    assert isinstance(result, ApplyResult)
    assert result.ok is True
    assert result.reason is None

    acl_file = tmp_path / "acl.conf"
    tmp_file = tmp_path / "acl.conf.tmp"
    assert acl_file.exists(), "acl.conf must be written"
    assert not tmp_file.exists(), "acl.conf.tmp must have been renamed away"
    assert result.path == acl_file

    content = acl_file.read_text(encoding="utf-8")
    assert "user amygdala" in content
    assert "user prefrontal_cortex" in content

    # SIGHUP sent to mosquitto container
    mock_docker_client.containers.get.assert_called_with("mosquitto")
    mock_docker_client.containers.get.return_value.kill.assert_called_once_with(
        signal="SIGHUP"
    )


@pytest.mark.asyncio
async def test_render_and_apply_conflict_short_circuits(
    acl_manager: AclManager,
    mock_docker_client: MagicMock,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    def fake_check(_self: AclManager, per_region: list[str]) -> str | None:
        return "dup topic-write claim"

    monkeypatch.setattr(AclManager, "_check_conflicts", fake_check)

    result = await acl_manager.render_and_apply()

    assert result.ok is False
    assert result.path is None
    assert result.reason is not None and "dup" in result.reason

    # No write, no broker reload.
    assert not (tmp_path / "acl.conf").exists()
    mock_docker_client.containers.get.return_value.kill.assert_not_called()


# ---------------------------------------------------------------------------
# reload_broker
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_reload_broker_sends_sighup(
    acl_manager: AclManager, mock_docker_client: MagicMock
) -> None:
    await acl_manager.reload_broker()
    mock_docker_client.containers.get.assert_called_with("mosquitto")
    mock_docker_client.containers.get.return_value.kill.assert_called_once_with(
        signal="SIGHUP"
    )


@pytest.mark.asyncio
async def test_reload_broker_container_not_found_raises_gliaerror(
    registry: RegionRegistry,
    tmp_path: Path,
) -> None:
    client = MagicMock()
    client.containers.get.side_effect = NotFound("no such container: mosquitto")
    mgr = AclManager(
        registry,
        docker_client=client,
        template_dir=REAL_TEMPLATE_DIR,
        bus_dir=tmp_path,
        reload_sleep_s=0.0,
    )
    with pytest.raises(GliaError):
        await mgr.reload_broker()


@pytest.mark.asyncio
async def test_reload_broker_api_error_wrapped(
    registry: RegionRegistry,
    tmp_path: Path,
) -> None:
    client = MagicMock()
    container = MagicMock()
    container.kill.side_effect = APIError("boom")
    client.containers.get.return_value = container
    mgr = AclManager(
        registry,
        docker_client=client,
        template_dir=REAL_TEMPLATE_DIR,
        bus_dir=tmp_path,
        reload_sleep_s=0.0,
    )
    with pytest.raises(GliaError):
        await mgr.reload_broker()


# ---------------------------------------------------------------------------
# ACL_PATH constant (sanity)
# ---------------------------------------------------------------------------


def test_module_constants_point_at_repo_bus_dir() -> None:
    assert ACL_PATH.name == "acl.conf"
    assert ACL_PATH.parent.name == "bus"
